version: '3.7'
services:
  postgres:
    image: postgres:12.3
    container_name: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c pg_stat_statements.max=100000 -c max_connections=200
volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
  mariadb_data:
    driver: local
  mysql_data:
    driver: local
  phpmyadmin_data:
    driver: local
