name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: actions/cache@v2
        with:
          path: |
            ~/.pnpm-store
            ~/.cache/pip
          key: pnpm-n-pip-cache-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-n-pip-cache-${{ hashFiles('pnpm-lock.yaml') }}
            pnpm-n-pip-cache-
      - name: Setup
        run: |
          pip install wheel setuptools pip -U
          npm i -g pnpm
          pnpm setup:ci
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2

      - run: pnpx nx workspace-lint
      - run: pnpx nx format:check
      - run: pnpx nx affected --target=lint --parallel=3
      - run: pnpx nx affected --target=test --parallel=3 --ci --code-coverage
      - run: pnpx nx affected --target=build --parallel=3